telegram:
  bot:
    username: "abstract_observer_bot"
    token: ${BOT_TOKEN}
    session:
      enable: true
      time-life:
        chat: 60
        user: 10
bot:
  admins:
    - 5975765192

dto-filler:
  packages-to-scan:
    - "com.github.lltal.observer"

enum-converter:
  packages-to-scan:
    - "com.github.lltal.observer"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/observer_bot
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect